# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  domain_name: example.com
  secret_key_base: 63ca7e00c7c61eca6a2aa224b6e2078a0a7e3ab85145de43bd923feacc9d8bcbcd192ae56b397ed8828497784411c358edec966c37d0633326c4bfdf47812232

test:
  secret_key_base: e2f44c5ab16834a32ae466ded5fe892d1ab1ca97df63ef72afcbd24177531a881790725b4ef7be0e58da7ffcda1a0182f2bb8e1150d71acbf04a6b2cc65db83e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
